import pygame

WIDTH = 1280
HEIGHT = 720
SIZE_SCREEN = (WIDTH, HEIGHT)

CENTER_X = WIDTH//2
CENTER_Y = HEIGHT//2
CENTER = (CENTER_X, CENTER_Y)

DISPLAY_LEFT = 0
DISPLAY_RIGHT = WIDTH
DISPLAY_TOP = 0
DISPLAY_BOTTOM = HEIGHT
DISPLAY_MIDTOP = (CENTER_X, DISPLAY_TOP)

SIZE_ICON = (32, 32)
ORIGIN = (0, 0)

FPS = 60

HOMER_SIZE = (150, 200)
HOMER_POS_INICIAL = (CENTER_X, HEIGHT)
HOMER_SPEED = 10

DONUT_SIZE = (80, 80)
DONUT_SPEED =  5

AZUL = pygame.color.Color(0,0,255)